# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Sabu George
title: Technical Lead / Solution Architect
email: sabugeorge.mec@gmail.com
phone: + 91-9650572511

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  sabsgeo
stackoverflow_username: "6583362"
linkedin_username: abu-george-1495a467

# Additional icon links
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/sabu.png
about_content: |  
  I am a self-motivated, enthusiastic, hands-on person who likes to get the hands dirty, solving problems in fields of cloud infrastructure/computing, website development, mobile app development, and embedded system development. I have 8+ years of industrial experience, of which 6+ years I worked with startups in different fields, exploring my interests. People who worked with me recognize me on my problem solving skills, system design ability, speed, and flexibility to learn new things, my agility on black box debugging, and explaining technology to non-tecnical people in simple language. My hobbies are traveling, having a lot of coffee, doing electronic, electrical, and home decor projects for my home.  
# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
    Trekking
    Cycling 
    Going for long driving 

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
